module.exports = [
    "What does a meaningful life look like to me?",
    "When was the last time I felt truly at peace?",
    "What parts of myself have I been hiding from others?",
    "If I had no fear, what would I do today?",
    "What are three values I want to live by?",
    "Am I proud of who I’ve become?",
    "What kind of legacy do I want to leave?",
    "What emotion do I avoid the most? Why?",
    "What does success look like for me—really?",
    "Who inspires me and why?",
    "What habits are silently shaping my future?",
    "What do I believe my purpose is right now?",
    "What am I pretending not to know?",
    "What do I need to forgive myself for?",
    "What was a moment I felt truly alive?",
    "How do I define love?",
    "Am I surrounding myself with people who help me grow?",
    "What am I most afraid of losing?",
    "When do I feel most confident in myself?",
    "What would I do differently if I could start over?",
    "What would I try if I knew I could not fail?",
    "Do I follow my heart or my head more often?",
    "What drains me the most lately?",
    "What lights me up and gives me energy?",
    "Who do I feel most like myself around?",
    "What patterns keep repeating in my life?",
    "How do I self-sabotage?",
    "What do I want that I'm afraid to admit?",
    "If my inner child could speak, what would they say?",
    "Am I being honest with myself?",
    "What does freedom mean to me?",
    "What have I outgrown that I’m still holding on to?",
    "What do I avoid because it’s uncomfortable?",
    "Where do I feel stuck right now?",
    "What limiting beliefs are holding me back?",
    "What would my ideal day look like?",
    "What am I truly passionate about?",
    "How do I react to failure?",
    "Who have I hurt, intentionally or not?",
    "What role does fear play in my decision-making?",
    "When do I feel most at peace with the world?",
    "What part of my past do I need to make peace with?",
    "What would I say to my future self?",
    "What does my relationship with time look like?",
    "When do I feel most in alignment?",
    "Am I living or just existing?",
    "What makes me feel fulfilled?",
    "What truths am I running from?",
    "Who do I need to set boundaries with?",
    "What does self-love mean to me?",
    "What do I need more of in my life?",
    "What does a healed version of me look like?",
    "Where am I placing my energy that doesn’t deserve it?",
    "What would I say to my younger self?",
    "Am I creating or consuming more?",
    "What lies have I accepted about myself?",
    "What does vulnerability mean to me?",
    "What keeps me from being authentic?",
    "What do I want to be remembered for?",
    "What roles do I play in other people's lives?",
    "How do I define spiritual growth?",
    "What am I learning about myself this season?",
    "What relationship patterns do I want to break?",
    "What dream have I let die that I want to revive?",
    "What does 'enough' look like to me?",
    "Do I know how to rest without guilt?",
    "What makes me feel small? Why?",
    "How do I react when I feel powerless?",
    "Where in my life do I feel most confident?",
    "What would I do if I had one year to live?",
    "What does balance look like in my life?",
    "How do I want to show up in my relationships?",
    "What’s something I’ve never told anyone?",
    "Am I more focused on proving or improving?",
    "What’s my relationship with control?",
    "What masks do I wear to feel safe?",
    "What lessons keep repeating until I learn them?",
    "When do I feel most creative?",
    "Where do I still feel broken?",
    "What does growth mean to me?",
    "How do I handle being misunderstood?",
    "Am I living by default or by design?",
    "What are three things I’m avoiding?",
    "What makes me feel truly alive?",
    "What are my most deeply held fears?",
    "What does happiness really look like for me?",
    "What’s one belief I need to let go of?",
    "What’s something I’m craving but not giving myself?",
    "What parts of my identity have I constructed for acceptance?",
    "When do I feel disconnected from myself?",
    "What does forgiveness look like for me?",
    "How do I nurture myself when I’m hurting?",
    "What’s one thing I wish others knew about me?",
    "Am I chasing goals that are truly mine?",
    "What am I most grateful for today?",
    "What moments have shaped me the most?",
    "When was I last truly present?",
    "What role does ego play in my choices?",
    "How do I cope with uncertainty?",
    "What’s my emotional home?",
    "What part of my life needs more honesty?",
    "Where do I feel the most resistance?",
    "What parts of myself do I still reject?",
    "What does healing feel like in my body?",
    "What emotion do I need to sit with more often?",
]